### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by jhenkins** [thunderox/triceratops#10]
Hello Nick,

After the recent preset update, the build process seems to be failing. I have tested the build on Ubuntu 20.04 LTS as well as Ubuntu Studio 21.04 with the same results. Here is the error when you do "waf configure":

```
$ ./configure_triceratops 
Setting top to                           : /home/jhenkins/projects/git/triceratops 
Setting out to                           : /home/jhenkins/projects/git/triceratops/build 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 

Global Configuration 
 * Install prefix                        : /usr/local 
 * Debuggable build                      : False 
 * Build documentation                   : False 

triceratops Configuration 
detected 64 bit architecture, enabling -fPIC
Checking for program 'pkg-config'        : /usr/bin/pkg-config 
Checking for 'lv2'                       : yes 
Checking for 'gtkmm-2.4'                 : yes 
Traceback (most recent call last):
  File "/home/jhenkins/projects/git/triceratops/.waf-2.0.19-1216edef773cb93a573c0abd4d9bece5/waflib/Scripting.py", line 119, in waf_entry_point
    run_commands()
  File "/home/jhenkins/projects/git/triceratops/.waf-2.0.19-1216edef773cb93a573c0abd4d9bece5/waflib/Scripting.py", line 182, in run_commands
    ctx=run_command(cmd_name)
  File "/home/jhenkins/projects/git/triceratops/.waf-2.0.19-1216edef773cb93a573c0abd4d9bece5/waflib/Scripting.py", line 173, in run_command
    ctx.execute()
  File "/home/jhenkins/projects/git/triceratops/.waf-2.0.19-1216edef773cb93a573c0abd4d9bece5/waflib/Configure.py", line 85, in execute
    super(ConfigurationContext,self).execute()
  File "/home/jhenkins/projects/git/triceratops/.waf-2.0.19-1216edef773cb93a573c0abd4d9bece5/waflib/Context.py", line 92, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/jhenkins/projects/git/triceratops/.waf-2.0.19-1216edef773cb93a573c0abd4d9bece5/waflib/Context.py", line 133, in recurse
    user_function(self)
  File "/home/jhenkins/projects/git/triceratops/wscript", line 47, in configure
    conf.env.LV2DIR = os.getenv('LV2_PATH').split(':')[2]
AttributeError: 'NoneType' object has no attribute 'split'
```

Also keep in mind that "python2" will be deprecated soon  - for instance Ubuntu 21.04 does not have it at all.

Cheers,
Jan

**Comment by thunderox** [comment]
Thanks for letting me know, has the old python 2 waf crept back in somehow, not sure how,  I'll check

**Comment by thunderox** [comment]
this is odd I've not been able to replicate those errors even typing "python3 waf configure", I'm using 20.04 on both machines.

**Comment by thunderox** [comment]
Thanks for looking at it again, I'll see if I can work it out over the next few days. Have been working on a new version using FalkTXs' DISTRHO which allows it to run within more hosts so yay for that. I'll maintain them in parallel until I'm sure this works reliably.
